import re
from spacy.lang.char_classes import LIST_ELLIPSES, LIST_ICONS, ALPHA_LOWER, ALPHA_UPPER, ALPHA, PUNCT
from spacy.lang.en.punctuation import TOKENIZER_INFIXES

# Extensive list of unwanted patterns
UNWANTED_PATTERNS = [
    re.compile(r'\bClick here*?\b', re.IGNORECASE),
    re.compile(r'Advertisement', re.IGNORECASE),
    re.compile(r'Subscribe', re.IGNORECASE),
    re.compile(r'Sign up', re.IGNORECASE),
    re.compile(r'Log[ -]?in', re.IGNORECASE),
    re.compile(r'Read more', re.IGNORECASE),
    re.compile(r'Next page', re.IGNORECASE),
    re.compile(r'Previous page', re.IGNORECASE),
    re.compile(r'Privacy policy', re.IGNORECASE),
    re.compile(r'Terms of (service|use)', re.IGNORECASE),
    re.compile(r'Cookie settings?', re.IGNORECASE),
    re.compile(r'Share (this|on)', re.IGNORECASE),
    re.compile(r'Follow us', re.IGNORECASE),
    re.compile(r'Related articles?', re.IGNORECASE),
    re.compile(r'Most popular', re.IGNORECASE),
    re.compile(r'Breaking news', re.IGNORECASE),
    re.compile(r"Editor's note", re.IGNORECASE),
    re.compile(r'Sponsored content', re.IGNORECASE),
    re.compile(r'©|&copy;|Copyright', re.IGNORECASE),
    re.compile(r'All rights reserved', re.IGNORECASE),
    re.compile(r'Contact us', re.IGNORECASE),
    re.compile(r'About us', re.IGNORECASE),
    re.compile(r'Back to top', re.IGNORECASE),
    re.compile(r'Latest updates?', re.IGNORECASE),
    re.compile(r'Live updates?', re.IGNORECASE),
    re.compile(r'Watch now', re.IGNORECASE),
    re.compile(r'Download now', re.IGNORECASE),
    re.compile(r'Get started', re.IGNORECASE),
    re.compile(r'Feedback', re.IGNORECASE),
    re.compile(r'Report', re.IGNORECASE),
    re.compile(r'Announcements?', re.IGNORECASE),
    re.compile(r'Disclaimer', re.IGNORECASE),
    re.compile(r'Menu', re.IGNORECASE),
    re.compile(r'Home', re.IGNORECASE),
    re.compile(r'Site map', re.IGNORECASE),
    re.compile(r'Donate', re.IGNORECASE),
    re.compile(r'Support us', re.IGNORECASE),
    re.compile(r'Careers?', re.IGNORECASE),
    re.compile(r'Partners?', re.IGNORECASE),
    re.compile(r'Jobs?', re.IGNORECASE),
    re.compile(r'Press releases?', re.IGNORECASE),
    re.compile(r'Search', re.IGNORECASE),
    re.compile(r'Shop', re.IGNORECASE),
    re.compile(r'Newsletter', re.IGNORECASE),
    re.compile(r'FAQ', re.IGNORECASE),
    re.compile(r'Help Center', re.IGNORECASE),
    re.compile(r'Username', re.IGNORECASE),
    re.compile(r'Password', re.IGNORECASE),
    re.compile(r'Forgot Password', re.IGNORECASE),
    re.compile(r'Notifications?', re.IGNORECASE),
    re.compile(r'RSS Feeds?', re.IGNORECASE),
    re.compile(r'Follow', re.IGNORECASE),
    re.compile(r'Unfollow', re.IGNORECASE),
    re.compile(r'Bookmark', re.IGNORECASE),
    re.compile(r'Save for Later', re.IGNORECASE),
    re.compile(r'Ad Choices', re.IGNORECASE),
    re.compile(r'Cookies?', re.IGNORECASE),
    re.compile(r'Advertise with us', re.IGNORECASE),
    re.compile(r'Closed Captioning', re.IGNORECASE),
    re.compile(r'Do Not Sell My Personal Information', re.IGNORECASE),
    re.compile(r'Accessibility', re.IGNORECASE),
    re.compile(r'Open in app', re.IGNORECASE),
    re.compile(r'App Store', re.IGNORECASE),
    re.compile(r'Google Play', re.IGNORECASE),
    re.compile(r'Loading\.\.\.', re.IGNORECASE),
    re.compile(r'Page \d+ of \d+', re.IGNORECASE),
    re.compile(r'Top Stories', re.IGNORECASE),
    re.compile(r'Editors Picks', re.IGNORECASE),
    re.compile(r'Next', re.IGNORECASE),
    re.compile(r'Previous', re.IGNORECASE),
    re.compile(r'View Comments?', re.IGNORECASE),
    re.compile(r'Add Comment', re.IGNORECASE),
    re.compile(r'Leave a Reply', re.IGNORECASE),
    re.compile(r'Back to Homepage', re.IGNORECASE),
    re.compile(r'Submit', re.IGNORECASE),
    re.compile(r'Login to Continue', re.IGNORECASE),
    re.compile(r'You might also like', re.IGNORECASE),
    re.compile(r'Advertisement', re.IGNORECASE),
    re.compile(r'Advertisements?', re.IGNORECASE),
    re.compile(r'Ads by', re.IGNORECASE),
    re.compile(r'Cookie Policy', re.IGNORECASE),
    re.compile(r'Accept Cookies', re.IGNORECASE),
    re.compile(r'Decline', re.IGNORECASE),
    re.compile(r'Accept', re.IGNORECASE),
    re.compile(r'Settings', re.IGNORECASE),
    re.compile(r'Newsletter Signup', re.IGNORECASE),
    re.compile(r'Enter your email', re.IGNORECASE),
    re.compile(r'Subscribe to our newsletter', re.IGNORECASE),
    re.compile(r'Subscribe Now', re.IGNORECASE),
    re.compile(r'Subscribe for more', re.IGNORECASE),
    re.compile(r'By continuing you agree to our', re.IGNORECASE),
    re.compile(r'Privacy Settings', re.IGNORECASE),
    re.compile(r'Contact Information', re.IGNORECASE),
    re.compile(r'Social Media', re.IGNORECASE),
    re.compile(r'Facebook', re.IGNORECASE),
    re.compile(r'Twitter', re.IGNORECASE),
    re.compile(r'Instagram', re.IGNORECASE),
    re.compile(r'LinkedIn', re.IGNORECASE),
    re.compile(r'YouTube', re.IGNORECASE),
    re.compile(r'Pinterest', re.IGNORECASE),
    re.compile(r'All Articles', re.IGNORECASE),
    re.compile(r'Load More', re.IGNORECASE),
    re.compile(r'See All', re.IGNORECASE),
    re.compile(r'Trending', re.IGNORECASE),
    re.compile(r'Most Read', re.IGNORECASE),
    re.compile(r'Most Shared', re.IGNORECASE),
    re.compile(r'Print', re.IGNORECASE),
    re.compile(r'Email', re.IGNORECASE),
    re.compile(r'PDF Version', re.IGNORECASE),
    re.compile(r'Author Bio', re.IGNORECASE),
    re.compile(r'Footer', re.IGNORECASE),
    re.compile(r'Header', re.IGNORECASE),
    re.compile(r'Skip to content', re.IGNORECASE),
    re.compile(r'Jump to navigation', re.IGNORECASE),
]


# Custom infixes
CUSTOM_INFIXES = TOKENIZER_INFIXES + [
    r'(?<=[0-9])-(?=[0-9])',          # Split numbers connected with hyphens (e.g., 123-456)
    r'(?<=[A-Za-z])-(?=[A-Za-z])',    # Split words connected with hyphens (e.g., state-of-the-art)
    r'(?<=[A-Za-z])\'(?=[A-Za-z])',   # Split contractions (e.g., can't, won't)
    r'(?<=[0-9])/(?=[0-9])',          # Split numbers connected with slashes (e.g., 2020/2021)
    r'(?<=[A-Za-z0-9])\.(?=[A-Za-z0-9])',  # Split words connected with periods (e.g., U.S.A.)
    r'(?<=[A-Za-z0-9])_(?=[A-Za-z0-9])',   # Split words connected with underscores
    r'(?<=[A-Za-z0-9])/(?=[A-Za-z0-9])',   # Split words connected with slashes
    r'(?<=[A-Za-z0-9])\:(?=[A-Za-z0-9])',  # Split words connected with colons
    r'(?<=[A-Za-z0-9])\,(?=[A-Za-z0-9])',  # Split words connected with commas
]